---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cr.undercloud.kr
  resources:
  - virtualmachinehosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cr.undercloud.kr
  resources:
  - virtualmachinehosts/finalizers
  verbs:
  - update
- apiGroups:
  - cr.undercloud.kr
  resources:
  - virtualmachinehosts/status
  verbs:
  - get
  - patch
  - update
